MERGE dbo.Shindig AS TARGET
USING (VALUES ('apicon-new-york-2025',                           1, 1, 3, 'US', 'NY', '2025-09-29', '2025-10-02', 'APIcon New York 2025',          'New York', 'New York Marriott at the Brooklyn Bridge', 'America/​New_York', 'https://apiconference.net/new-york/'),
              ('devopscon-new-york-2025',                        1, 1, 3, 'US', 'NY', '2025-09-29', '2025-10-02', 'DevOps Con New York 2025',      'New York', 'New York Marriott at the Brooklyn Bridge', 'America/​New_York', 'https://devopscon.io/new-york/'),
              ('techoroma-netherlands-2025',                     1, 1, 3, 'NL', 'UT', '2025-10-27', '2025-10-29', 'Techorama 2025 Netherlands',    'Urecht',   'Kinepolis Jaarbeurs Utrecht',              'Europe/​Amsterdam', 'https://www.techorama.nl/'),
              ('prairie-dev-con-winnipeg-2025',                  1, 1, 3, 'CA', 'MB', '2025-09-22', '2025-09-23', 'Prairie Dev Con 2025 Winnipeg', 'Winnipeg', 'Canad Inns Destination Centre Polo Park',  'America/​Winnipeg', 'https://www.prairiedevcon.com/'),
              ('ncd-porto-2025',                                 1, 1, 3, 'PT', '13', '2025-10-20', '2025-10-24', 'NDC Porto 2025',                'Porto',    'Alfândega Porto Congress Centre',          'Europe/​Lisbon',    'https://ndcporto.com/'),
              ('apicon-berlin-2025',                             1, 1, 3, 'DE', 'BE', '2025-10-21', '2025-10-23', 'APIcon Berlin 2025',            'Berlin',   'Maritim proArte Hotel',                    'Europe/​Berlin',    'https://apiconference.net/berlin/'),
              ('serverless-architecture-conference-berlin-2025', 1, 1, 3, 'DE', 'BE', '2025-10-21', '2025-10-23', 'APIcon Berlin 2025',            'Berlin',   'Maritim proArte Hotel',                    'Europe/​Berlin',    'https://apiconference.net/berlin/'),
              ('build-stuff-2025',                               1, 1, 3, 'LT', '58', '2025-12-03', '2025-12-05', 'Build Stuff 2025',              'Vilnius',   'Radisson Blu Hotel Lietuva',              'Europe/​Vilnius',   'https://buildstuff.events/'))
AS SOURCE (Permalink,
           IsEnabled,
           ShindigTypeId,
           ShindigStatusId,
           CountryCode,
           CountryDivisionCode,
           StartDate,
           EndDate,
           ShindigName,
           City,
           Venue,
           TimeZoneId,
           ShindigUrl)
ON TARGET.Permalink = SOURCE.Permalink
WHEN MATCHED THEN UPDATE SET TARGET.ShindigTypeId       = SOURCE.ShindigTypeId,
                             TARGET.ShindigStatusId     = SOURCE.ShindigStatusId,
                             TARGET.ShindigName         = SOURCE.ShindigName,
                             TARGET.CountryCode         = SOURCE.CountryCode,
                             TARGET.CountryDivisionCode = SOURCE.CountryDivisionCode,
                             TARGET.City                = SOURCE.City,
                             TARGET.Venue               = SOURCE.Venue,
                             TARGET.StartDate           = SOURCE.StartDate,
                             TARGET.EndDate             = SOURCE.EndDate,
                             TARGET.TimeZoneId          = SOURCE.TimeZoneId,
                             TARGET.ShindigUrl          = SOURCE.ShindigUrl,
                             TARGET.IsEnabled           = SOURCE.IsEnabled
WHEN NOT MATCHED THEN INSERT (Permalink,
                              ShindigTypeId,
                              ShindigStatusId,
                              ShindigName,
                              CountryCode,
                              CountryDivisionCode,
                              City,
                              Venue,
                              StartDate,
                              EndDate,
                              TimeZoneId,
                              ShindigUrl,
                              IsEnabled)
                      VALUES (SOURCE.Permalink,
                              SOURCE.ShindigTypeId,
                              SOURCE.ShindigStatusId,
                              SOURCE.ShindigName,
                              SOURCE.CountryCode,
                              SOURCE.CountryDivisionCode,
                              SOURCE.City,
                              SOURCE.Venue,
                              SOURCE.StartDate,
                              SOURCE.EndDate,
                              SOURCE.TimeZoneId,
                              SOURCE.ShindigUrl,
                              SOURCE.IsEnabled)
WHEN NOT MATCHED BY SOURCE THEN DELETE;
GO