global using Azure.Identity;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.Configuration.AzureAppConfiguration;
global using Octokit;
global using Spectre.Console;
global using SQLData;
global using SQLData.Models;
global using System.Text;